  return (<div style={{ background: '#fff' }}>
    

    {/* HERO */}
    {banners.length > 0 ? (
      <HeroCarousel slides={banners.map((b: any) => ({ title: b.title, subtitle: b.subtitle, image: b.image, link: b.link, button_text: b.button_text }))} />
    ) : (
      <section className="ug-hero" style={{ background: '#000', minHeight: '60vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><div style={{ textAlign: 'center', color: '#fff' }}><p style={{ fontSize: 24, fontWeight: 200, marginBottom: 16 }}>{t('no_banners')}</p><p style={{ fontSize: 14, color: '#8d8d86' }}>{t('add_banners')}</p></div></section>
    )}

    {/* MARQUEE */}
    {show('show_marquee') && <div style={{ background: '#D63F1C', padding: '14px 0', overflow: 'hidden' }}><div className="animate-marquee" style={{ display: 'flex', whiteSpace: 'nowrap' }}>{[...Array(3)].map((_, i) => <span key={i} style={{ color: '#000', fontWeight: 600, fontSize: 14, letterSpacing: '0.05em', margin: '0 32px' }}>★ {s('marquee_text')} ★</span>)}</div></div>}

    {/* HOW IT WORKS */}
    {show('show_how') && <section id="how-it-works" className="ug-section" style={{ padding: '120px 0', background: '#f5f1ea' }}><div className="ug-container" style={{ maxWidth: 1400, margin: '0 auto', padding: '0 48px' }}><p style={{ fontSize: 12, letterSpacing: '0.2em', color: '#D63F1C', fontWeight: 500, marginBottom: 12, textTransform: 'uppercase' }}>02 / {s('how_title', t('how_it_works'))}</p><p style={{ fontSize: 18, color: '#77736b', maxWidth: 560, marginBottom: 60 }}>{s('how_desc', t('how_works_desc'))}</p><div className="ug-grid-3" style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 24 }}>{[{ step: '01', title: s('step1_title', t('plug_in')), desc: s('step1_desc', t('usb_power')) },{ step: '02', title: s('step2_title', t('place_car')), desc: s('step2_desc', t('works_all')) },{ step: '03', title: s('step3_title', t('enjoy_drift')), desc: s('step3_desc', t('smooth_360')) }].map(item => <div key={item.step} style={{ padding: 40, background: '#fff', border: '1px solid #dfdfdf', position: 'relative' }}><span style={{ fontSize: 48, fontWeight: 200, color: '#e0dbd2', position: 'absolute', top: 24, right: 32 }}>{item.step}</span><h3 style={{ fontSize: 18, fontWeight: 500, color: '#14140f', marginBottom: 8, position: 'relative', zIndex: 1 }}>{item.title}</h3><p style={{ fontSize: 14, color: '#77736b', position: 'relative', zIndex: 1 }}>{item.desc}</p></div>)}</div></div></section>}

    {/* FEATURED */}
    {show('show_featured') && products.length > 0 && <section className="ug-section" style={{ padding: '120px 0', background: '#fff' }}><div className="ug-container" style={{ maxWidth: 1400, margin: '0 auto', padding: '0 48px' }}><p style={{ fontSize: 12, letterSpacing: '0.2em', color: '#D63F1C', fontWeight: 500, marginBottom: 12, textTransform: 'uppercase' }}>03 / {t('featured')}</p><h2 style={{ fontSize: 'clamp(36px, 5vw, 56px)', fontWeight: 200, color: '#14140f', marginBottom: 12 }}>{s('featured_title', '')}</h2><p style={{ fontSize: 18, color: '#77736b', marginBottom: 64 }}>{s('featured_subtitle', '')}</p><div className="ug-featured-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 64, alignItems: 'center' }}><Link href={`/products/${products[0].slug}`} style={{ aspectRatio: '4/3', background: '#e8e3da', backgroundImage: getImg(products[0]) ? `url(${getImg(products[0])})` : 'none', backgroundSize: 'cover', backgroundPosition: 'center', display: 'block' }} /><div><h3 style={{ fontSize: 24, fontWeight: 500, color: '#14140f', marginBottom: 12 }}>{products[0].name}</h3><div style={{ display: 'flex', gap: 2, marginBottom: 16 }}>{[...Array(5)].map((_, i) => <span key={i} style={{ color: i < 4 ? '#D63F1C' : '#dfdfdf', fontSize: 18 }}>{i < 4 ? '★' : '☆'}</span>)}<span style={{ fontSize: 14, color: '#77736b', marginLeft: 8 }}>128 {t('reviews')}</span></div><p style={{ fontSize: 14, color: '#77736b', lineHeight: 1.7, marginBottom: 24 }}>{products[0].description}</p><div style={{ display: 'flex', alignItems: 'baseline', gap: 12, marginBottom: 24 }}><span style={{ fontSize: 32, fontWeight: 500, color: '#14140f' }}>{formatPrice(products[0].price)}</span>{products[0].compare_at_price && products[0].compare_at_price > products[0].price && <span style={{ fontSize: 18, color: '#9a978d', textDecoration: 'line-through' }}>{formatPrice(products[0].compare_at_price)}</span>}</div><Link href={`/products/${products[0].slug}`} style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: '#D63F1C', color: '#fff', border: 'none', padding: '16px 40px', fontSize: 16, fontWeight: 500, textDecoration: 'none' }}>{t('buy_now')} — {formatPrice(products[0].price)} <span>→</span></Link></div></div></div></section>}

    {/* PRODUCTS */}
    {show('show_products') && <section className="ug-section" style={{ padding: '120px 0', background: '#f5f1ea' }}><div className="ug-container" style={{ maxWidth: 1400, margin: '0 auto', padding: '0 48px' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 48 }}><div><p style={{ fontSize: 12, letterSpacing: '0.2em', color: '#D63F1C', fontWeight: 500, marginBottom: 12, textTransform: 'uppercase' }}>04 / Shop All</p><h2 style={{ fontSize: 'clamp(28px, 4vw, 42px)', fontWeight: 200, color: '#14140f' }}>{t('shop_collection')}</h2></div><Link href="/products" style={{ fontSize: 14, color: '#77736b', textDecoration: 'none' }}>{t('view_all')} →</Link></div><div className="ug-grid-3" style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 32 }}>{products.map((p: any) => <ProductCard key={p.id} product={p} />)}</div></div></section>}

    {/* STORY */}
    {show('show_story') && <section className="ug-section" style={{ padding: '120px 0', background: '#fff' }}><div className="ug-container" style={{ maxWidth: 1400, margin: '0 auto', padding: '0 48px' }}><div style={{ maxWidth: 640 }}><p style={{ fontSize: 12, letterSpacing: '0.2em', color: '#D63F1C', fontWeight: 500, marginBottom: 24, textTransform: 'uppercase' }}>07 / {t('story')}</p><p style={{ fontSize: 14, color: '#9a978d', marginBottom: 8 }}>— {s('story_founder', '')}</p><p style={{ fontSize: 20, color: '#4a4a40', lineHeight: 1.6, marginBottom: 24 }}>{s('story_text', '')}</p>{s('story_video') && <div style={{ marginTop: 16 }}><video src={s('story_video')} controls style={{ width: '100%', maxHeight: 400 }} /></div>}</div></div></section>}

    {/* VOICES */}
    {show('show_voices') && <section className="ug-section" style={{ padding: '120px 0', background: '#f5f1ea' }}><div className="ug-container" style={{ maxWidth: 1400, margin: '0 auto', padding: '0 48px' }}><p style={{ fontSize: 12, letterSpacing: '0.2em', color: '#D63F1C', fontWeight: 500, marginBottom: 12, textTransform: 'uppercase' }}>08 / VOICES</p><h2 style={{ fontSize: 'clamp(28px, 4vw, 42px)', fontWeight: 200, color: '#14140f', marginBottom: 48 }}>{s('voices_title', 'VOICES OF OUR CUSTOMERS')}</h2><div className="ug-grid-3" style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 32 }}>{[1, 2, 3].map(n => { const name = s('voice' + n + '_name', ''); const text = s('voice' + n + '_text', ''); const media = s('voice' + n + '_media', ''); if (!name && !text) return null; const isVid = media && /\.(mp4|webm|ogg)$/i.test(media); return <div key={n} style={{ background: '#fff', padding: 32, border: '1px solid #dfdfdf' }}>{media && <div style={{ width: '100%', aspectRatio: '16/9', background: '#f5f1ea', marginBottom: 20, overflow: 'hidden' }}>{isVid ? <video src={media} muted controls style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : <img src={media} style={{ width: '100%', height: '100%', objectFit: 'cover' }} alt="" />}</div>}<p style={{ fontSize: 16, color: '#4a4a40', lineHeight: 1.7, fontStyle: 'italic', marginBottom: 16 }}>&ldquo;{text}&rdquo;</p><p style={{ fontSize: 14, fontWeight: 600, color: '#14140f' }}>— {name}</p></div>; })}</div></div></section>}

    <style jsx>{`
      @media (max-width: 768px) {
        .ug-section { padding: 40px 0 !important; }
        .ug-container { padding: 0 16px !important; }
        .ug-grid-3 { grid-template-columns: 1fr !important; gap: 12px !important; }
        .ug-featured-grid { grid-template-columns: 1fr !important; gap: 24px !important; }
        .ug-hero { min-height: 35vh !important; }
      }
    `}</style>
  </div>);
